#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl -p unzip

# This script is copied from Nixpkgs with minor tweaks.

set -eu
set -o pipefail

root=$(pwd)

if [[ ! -f ./update.sh ]]; then
    echo "Please run this script from within 'static/highlightjs'!"
    exit 1
fi

scratch=$(mktemp -d -t tmp.XXXXXXXXXX)
function finish {
  rm -rf "$scratch"
}
trap finish EXIT

mkdir $scratch/src
cd $scratch/src

token=$(curl https://highlightjs.org/download/ -c "$scratch/jar" \
    | grep csrf \
    | cut -d"'" -f6)

curl --header "Referer: https://highlightjs.org/download/"\
    -b "$scratch/jar" \
    --data "csrfmiddlewaretoken=$token&nix.js=on&bash.js=on&shell.js=on" \
    https://highlightjs.org/download/ > $scratch/out.zip

unzip "$scratch/out.zip"
out="$root/"
mkdir -p "$out"
cp ./{highlight.pack.js,LICENSE,styles/agate.css} "$out"

(
    echo "This file was generated by 'static/highlightjs/update.sh'"
    echo ""
    cat README.md
) > "$out/README.md"
